[package]
name = "dnld"
version = "0.2.0"
edition = "2021"
description = "Rust library for simple downloading"
repository = "https://github.com/qtfkwk/dnld"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
reqwest = { version = "0.12.15", features = ["blocking"] }
