[package]
name = "dnld"
version = "0.1.5"
edition = "2021"
description = "Rust library for simple downloading"
repository = "https://github.com/qtfkwk/dnld"
license = "MIT"

[dependencies]
anyhow = "1.0.91"
bytes = "1.8.0"
reqwest = { version = "0.12.8", features = ["blocking"] }
